<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html lang="it">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="language" content="italian">
<link href="/community/linuxit2.css" rel="stylesheet" type="text/css">
<meta name="Keywords" content="ILS, Linux, LUG, LUG Map, Linux in Italia, Italia, Software Libero, Italian Linux Society">
<title>Mappa dei Linux User Group e Free Software User Group Italiani</title>
</head>
<body bgcolor="#FFFFFF" text="#000000" link="#FF0000" vlink="#AA0000" alink="#00AA00">
<!-- div align=center>
<table border=0 cellspacing=0 cellpadding=2 width="100%" align=center class=bdouble >
<tr>
 <td width="10%" align=center><a href="/">Home</a></td>
 <td width="10%" align=center><a href="/ILS/">ILS</a></td>
 <td width="10%" align=center><a href="/GNU/">GNU</a></td>
 <td width="10%" align=center><a href="/LUG/">LUG</a></td>
 <td width="10%" align=center><a href="/LinuxDay/main.shtml">Linux Day</a></td>
 <td width="10%" align=center><a href="http://lugware.linux.it/faq.php">LugWare</a></td>
 <td width="10%" align=center><a href="http://cvs.linux.it/" >CVS</a></td>
 <td width="10%" align=center><a href="/info/">Informazioni</a></td>
 <td width="10%" align=center><a href="http://lists.linux.it/listinfo/" >Mailing List</a></td>
 <td width="10%" align=center><a href="/ospiti/">Ospiti</a></td>
 <td width="10%" align=center><a href="/contattaci.shtml">Contattaci</a></td>
</tr>
</table>
<img src="/images/logo-ils2.jpg" alt="[Italian Linux Society]" height=90 width=728 align=middle>
</div -->
<h2 align=center>LUG presenti in Valle d'Aosta</h2><div align=right>&raquo; <a href="index.phtml">torna alla LUGmap</a></div><br>
<table width="100%" border=0 cellspacing=0 cellpadding=1 bgcolor="black"><tr><td>
<table width="100%" border=0 cellspacing=0 cellpadding=4 bgcolor="#00659c">
<tr class=menubox><th>Denominazione</th><th>Tipo</th><th>Area di attivit&agrave;</th><th>Fondazione</th><th>Homepage</th><th>Informazioni</th></tr>
<tr bgcolor="#dddddd">
<td align=center>SLAG</td>
<td align=center>Associazione</td>
<td align=center>Valle d'Aosta</td>
<td align=center>Novembre 2003</td>
<td align=center><a href="http://www.slag.it">www.slag.it</a></td>
<td width=300>Associazione culturale SLAG - Software Libero Aosta GLUG</td>
</tr>
</table>
</td></tr></table>
<p align=right>&raquo; <a href="index.phtml">torna alla LUGmap</a></p>

<!-- Footer --><p><hr size=1 noshade></body></html>
