<?php

require_once ('../utils.php');
lugheader ('LugMap Forge', 'scripts, widget, widget web');

?>

<p>
  Come tutti sappiamo la disponibilità di open-data permette la creazione di infinite applicazioni nuove e l'aggregazione delle informazioni
  in combinazioni inedite. Per questo motivo tutte le informazioni sui Linux User Group italiani pubblicate su questo sito sono accessibili
  in formato raw, formattate in files facilmente parsabili ed individualmente rintracciabili in modo programmatico.
</p>

<p>
  Di seguito, una lista di sotto-progetti realizzati scomponendo e ricomponendo in modo creativo questi dati.
</p>

<ul>
  <li><a href="lug-o-matic">Widget web con la lista dei LUG di una regione a scelta, da includere nel proprio sito</a></li>
  <li><a href="opml-generator">Script per isolare gli URL dei feeds RSS dei siti dei LUG indicizzati</a></li>
</ul>

<p>
  Di seguito, una lista di altri possibili spunti per nuovi "mashups" della LugMap. Contribuisci implementando una di queste idee!
</p>

<ul>
  <li>Plugin Wordpress con la lista dei LUG di una regione a scelta</li>
  <li>Plugin Drupal con la lista dei LUG di una regione a scelta</li>
  <li>Plugin MediaWiki con la lista dei LUG di una regione a scelta</li>
</ul>

<?php
  lugfooter ();
?>
