# -*- coding: utf-8  -*-
import config, family, urllib

#
# The Uncyclomedia family, assorted encyclopedi.as from the Uncyclopedia series.
# This file contains a full set of (currently) fifty languages, excluding forks,
# redirects and mirrors.
#
# Note that some of the wikia in this set are known to have badly incomplete,
# missing or incorrect interwiki maps. Do *not* attempt to invoke interwiki.py
# on Uncyclopedia-related wikis unless you have verified availability of
# links for all language pairs that you will plan to use as interwikis.
#

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'uncyclopedia'

        self.langs = {
            'ar': 'beidipedia.wikia.com',
            'ast':'nunyepedia.wikia.com',
            'bg': 'bg.oxypedia.net',
            'bn': 'bn.uncyc.org',
            'bs': 'bs.neciklopedija.org',
            'ca': 'valenciclopedia.wikia.com',
            'common': 'commons.uncyclomedia.org',
            'cs': 'necyklopedie.wikia.com',
            #'cy': 'cy.uncyclopedia.org.uk',
            'da': 'spademanns.wikia.com',
            'de': 'de.uncyclopedia.org',
            'el': 'frikipaideia.wikia.com',
            'en': 'uncyclopedia.wikia.com',
            'eo': 'neciklopedio.wikia.com',
            'es': 'inciclopedia.wikia.com',
            'et': 'ebatsuklopeedia.org',
            'fa': 'fa.uncyc.org',
            'fi': 'hikipedia.info',
            'fr': 'desencyclopedie.wikia.com',
            'ga': 'ga.uncyc.org',
            'got':'unsaiklopedia.org',
            'he': 'eincyclopedia.wikia.com',
            'hr': 'hr.neciklopedija.org',
            'hu': 'unciklopedia.org',
            'id': 'tolololpedia.wikia.com',
            'info': 'uncyclopedia.info',
            'it': 'nonciclopedia.wikia.com',
            'ja': 'ansaikuropedia.org',
            'jv': 'ndhablek.wikia.com',
            'ka': 'anciklopedia.org',
            'km': 'km.uncyclopedia.info',
            'ko': 'uncyclopedia.kr',
            'la': 'uncapaedia.wikia.com',
            'lb': 'kengencyclopedia.org',
            'li': 'kwatsjpedia.org',
            'lo': 'lo.uncyclopedia.info',
            'lt': 'juokopedija.org',
            'lv': 'lv.neciklopedija.org',
            'meta': 'meta.uncyclomedia.org',
            'mg': 'hatsiklopedia.org',
            'mk': 'mk.neciklopedija.org',
            'mo': 'neciclopedia.org',
            'ms': 'bodohpedia.org',
            'nl': 'oncyclopedia.net',
            'nn': 'ikkepedia.org',
            'no': 'ikkepedia.org',
            'oc': 'oisquipedia.org',
            'pl': 'nonsensopedia.wikia.com',
            'pt': 'desciclopedia.org',
            'ro': 'uncyclopedia.ro',
            'ru': 'absurdopedia.wikia.com',
            'sk': 'necyklopedia.wikia.com',
            'sl': 'butalopedija.org',
            'sr': 'sr.neciklopedija.org',
            'su': 'su.goblogpedia.wikia.com',
            'sv': 'psyklopedin.org',
            'th': 'th.uncyclopedia.info',
            'tl': 'pekepedia.net',
            'tr': 'yansiklopedi.org',
            'uk': 'inciklopedia.org',
            'yi': 'keinziklopedie.wikia.com',
            'zh-hk': 'uncyclopedia.hk',
            'zh-tw':'uncyclopedia.tw',
            'zh': 'zh.uncyclopedia.wikia.com',
            'zombie': 'zombie.pedia.ws',
        }

        #
        # project namespaces & custom namespace lists
        #

        self.namespaces[-2] = {
            '_default': u'Media',
            'ar': u'ميديا',
            'bg': u'Медия',
            'bn': u'মিডিয়া',
            'bs': u'Mediji',
            'cs': u'Média',
            'el': u'Μέσο',
            'et': u'Meedia',
            'fa': u'مدیا',
            'fr': u'Média',
            'ga': u'Meán',
            'he': u'מדיה',
            'hr': u'Mediji',
            'hu': u'Média',
            'ja': u'メディア',
            'ka': u'მედია',
            'km': u'មេឌា',
            'ko': u'미디어',
            'lo': u'ສື່',
            'lt': u'Medija',
            'mg': u'Rakitra',
            'mk': u'Медија',
            'nn': u'Medium',
            'no': u'Medium',
            'oc': u'Mèdia',
            'ru': u'Медиа',
            'sk': u'Médiá',
            'sl': u'Datoteka',
            'sr': u'Медија',
            'su': u'Média',
            'th': u'สื่อ',
            'tl': u'Midya',
            'tr': u'Medya',
            'uk': u'Медіа',
            'yi': u'מעדיע',
            'zh-hk': u'媒體',
            'zh-tw': u'媒體',
        }

        self.namespaces[-1] = {
            '_default': u'Special',
            'ar': u'خاص',
            'ast': u'Especial',
            'bg': u'Специални',
            'bn': u'বিশেষ',
            'bs': u'Posebno',
            'ca': u'Especial',
            'cs': u'Speciální',
            'da': u'Speciel',
            'de': u'Spezial',
            'el': u'Ειδικό',
            'eo': u'Speciala',
            'es': u'Especial',
            'et': u'Eri',
            'fa': u'ویژه',
            'fi': u'Toiminnot',
            'fr': u'Spécial',
            'ga': u'Speisialta',
            'he': u'מיוחד',
            'hr': u'Posebno',
            'hu': u'Speciális',
            'id': u'Istimewa',
            'it': u'Speciale',
            'ja': u'特別',
            'jv': u'Astamiwa',
            'ka': u'სპეციალური',
            'km': u'ពិសេស',
            'ko': u'특수기능',
            'la': u'Specialis',
            'lb': u'Spezial',
            'li': u'Speciaal',
            'lo': u'ພິເສດ',
            'lt': u'Specialus',
            'mg': u'Manokana',
            'mk': u'Специјални',
            'ms': u'Khas',
            'nl': u'Speciaal',
            'nn': u'Spesial',
            'no': u'Spesial',
            'oc': u'Especial',
            'pl': u'Specjalna',
            'pt': u'Especial',
            'ru': u'Служебная',
            'sk': u'Špeciálne',
            'sl': u'Posebno',
            'sr': u'Посебно',
            'su': u'Husus',
            'th': u'พิเศษ',
            'tl': u'Natatangi',
            'tr': u'Özel',
            'uk': u'Спеціальна',
            'yi': u'באַזונדער',
            'zh-hk': u'特殊',
            'zh-tw': u'特殊',
        }

        self.namespaces[1] = {
            '_default': u'Talk',
            'ar': u'نقاش',
            'ast': u'Alderique',
            'bg': u'Беседа',
            'bn': u'আলাপ',
            'bs': u'Razgovor',
            'ca': u'Discussió',
            'cs': u'Diskuse',
            'da': u'Diskussion',
            'de': u'Diskussion',
            'el': u'Συζήτηση',
            'eo': u'Diskuto',
            'es': u'Discusión',
            'et': u'Arutelu',
            'fa': u'بحث',
            'fi': u'Keskustelu',
            'fr': u'Discussion',
            'ga': u'Plé',
            'he': u'שיחה',
            'hr': u'Razgovor',
            'hu': u'Vita',
            'id': u'Pembicaraan',
            'it': u'Discussione',
            'ja': u'ノート',
            'jv': u'Dhiskusi',
            'ka': u'განხილვა',
            'km': u'ការពិភាក្សា',
            'ko': u'토론',
            'la': u'Disputatio',
            'lb': u'Diskussioun',
            'li': u'Euverlèk',
            'lo': u'ສົນທະນາ',
            'lt': u'Aptarimas',
            'lv': u'Diskusija',
            'mg': u'Dinika',
            'mk': u'Разговор',
            'mo': u'Discuţie',
            'ms': u'Perbincangan',
            'nl': u'Overleg',
            'nn': u'Diskusjon',
            'no': u'Diskusjon',
            'oc': u'Discutir',
            'pl': u'Dyskusja',
            'pt': u'Discussão',
            'ro': u'Discuţie',
            'ru': u'Обсуждение',
            'sk': u'Diskusia',
            'sl': u'Pogovor',
            'sr': u'Разговор',
            'su': u'Obrolan',
            'sv': u'Diskussion',
            'th': u'พูดคุย',
            'tl': u'Usapan',
            'tr': u'Tartışma',
            'uk': u'Обговорення',
            'yi': u'רעדן',
            'zh-hk': u'討論',
            'zh-tw': u'討論',
        }

        self.namespaces[2] = {
            '_default': u'User',
            'ar': u'مستخدم',
            'ast': u'Usuariu',
            'bg': u'Потребител',
            'bn': u'ব্যবহারকারী',
            'bs': u'Korisnik',
            'ca': u'Usuari',
            'cs': u'Uživatel',
            'da': u'Bruger',
            'de': u'Benutzer',
            'el': u'Χρήστης',
            'eo': u'Vikipediisto',
            'es': u'Usuario',
            'et': u'Kasutaja',
            'fa': u'کاربر',
            'fi': u'Käyttäjä',
            'fr': u'Utilisateur',
            'ga': u'Úsáideoir',
            'he': u'משתמש',
            'hr': u'Suradnik',
            'hu': u'Szerkesztő',
            'id': u'Pengguna',
            'it': u'Utente',
            'ja': u'利用者',
            'jv': u'Panganggo',
            'ka': u'მომხმარებელი',
            'km': u'អ្នកប្រើប្រាស់',
            'ko': u'사용자',
            'la': u'Usor',
            'lb': u'Benotzer',
            'li': u'Gebroeker',
            'lo': u'ຜູ້ໃຊ້',
            'lt': u'Naudotojas',
            'lv': u'Lietotājs',
            'mg': u'Mpikambana',
            'mk': u'Корисник',
            'mo': u'Utilizator',
            'ms': u'Pengguna',
            'nl': u'Gebruiker',
            'nn': u'Bruker',
            'no': u'Bruker',
            'oc': u'Utilizaire',
            'pl': u'Użytkownik',
            'pt': u'Usuário',
            'ro': u'Utilizator',
            'ru': u'Участник',
            'sk': u'Redaktor',
            'sl': u'Uporabnik',
            'sr': u'Корисник',
            'su': u'Pamaké',
            'sv': u'Användare',
            'th': u'ผู้ใช้',
            'tl': u'Tagagamit',
            'tr': u'Kullanıcı',
            'uk': u'Користувач',
            'yi': u'באַניצער',
            'zh-hk': u'用戶',
            'zh-tw': u'用戶',
        }

        self.namespaces[3] = {
            '_default': u'User talk',
            'ar': u'نقاش المستخدم',
            'ast': u'Usuariu alderique',
            'bg': u'Потребител беседа',
            'bn': u'ব্যবহারকারী আলাপ',
            'bs': u'Razgovor sa korisnikom',
            'ca': u'Usuari Discussió',
            'cs': u'Uživatel diskuse',
            'da': u'Brugerdiskussion',
            'de': u'Benutzer Diskussion',
            'el': u'Συζήτηση χρήστη',
            'eo': u'Vikipediista diskuto',
            'es': u'Usuario Discusión',
            'et': u'Kasutaja arutelu',
            'fa': u'بحث کاربر',
            'fi': u'Keskustelu käyttäjästä',
            'fr': u'Discussion utilisateur',
            'ga': u'Plé úsáideora',
            'he': u'שיחת משתמש',
            'hr': u'Razgovor sa suradnikom',
            'hu': u'Szerkesztővita',
            'id': u'Pembicaraan Pengguna',
            'it': u'Discussioni utente',
            'ja': u'利用者‐会話',
            'jv': u'Dhiskusi Panganggo',
            'ka': u'მომხმარებლის განხილვა',
            'km': u'ការពិភាក្សារបស់អ្នកប្រើប្រាស់',
            'ko': u'사용자토론',
            'la': u'Disputatio Usoris',
            'lb': u'Benotzer Diskussioun',
            'li': u'Euverlèk gebroeker',
            'lo': u'ສົນທະນາຂອງຜູ້ໃຊ້',
            'lt': u'Naudotojo aptarimas',
            'lv': u'Lietotāja diskusija',
            'mg': u'Dinika amin\'ny mpikambana',
            'mk': u'Разговор со корисник',
            'mo': u'Discuţie Utilizator',
            'ms': u'Perbincangan Pengguna',
            'nl': u'Overleg gebruiker',
            'nn': u'Brukerdiskusjon',
            'no': u'Brukerdiskusjon',
            'oc': u'Discussion Utilizaire',
            'pl': u'Dyskusja użytkownika',
            'pt': u'Usuário Discussão',
            'ro': u'Discuţie Utilizator',
            'ru': u'Обсуждение участника',
            'sk': u'Diskusia s redaktorom',
            'sl': u'Uporabniški pogovor',
            'sr': u'Разговор са корисником',
            'su': u'Obrolan pamaké',
            'sv': u'Användardiskussion',
            'th': u'คุยกับผู้ใช้',
            'tl': u'Usapang tagagamit',
            'tr': u'Kullanıcı mesaj',
            'uk': u'Обговорення користувача',
            'yi': u'באַניצער רעדן',
            'zh-hk': u'用戶討論',
            'zh-tw': u'用戶討論',
        }

        self.namespaces[4] = {
            '_default': u'Uncyclopedia',
            'ar': u'بيضيپيديا',
            'ast': u'Nunyepedia',
            'bg': u'Oxypedia',
            'bn': u'আনসাইক্লোপিডিয়া',
            'bs': u'Neciklopedija',
            'ca': u'Valenciclopèdia',
            'common': u'UnCommons',
            'cs': u'Necyklopedie',
            'cy': u'Celwyddoniadur',
            'da': u'Spademanns Leksikon',
            'el': u'Φρικηπαίδεια',
            'eo': u'Neciklopedio',
            'es': u'Inciclopedia',
            'et': u'Ebatsüklopeedia',
            'fa': u'نانشنامه',
            'fi': u'Hikipedia',
            'fr': u'Désencyclopédie',
            'ga': u'Frithchiclipéid',
            'got': u'Unsaiklopedia',
            'he': u'איןציקלופדיה',
            'hr': u'Neciklopedija',
            'hu': u'Unciklopédia',
            'id': u'Tolololpedia',
            'info': u'Uncyclopaedia',
            'it': u'Nonciclopedia',
            'jv': u'Ndhablek',
            'ka': u'Anciklopedia',
            'ko': u'백괴사전',
            'la': u'Uncapaedia',
            'lb': u'Kengencyclopedia',
            'li': u'Kwatsjpedia',
            'lt': u'Juokopediją',
            'lv': u'Neciklopēdija',
            'meta': u'UnMeta',
            'mg': u'Hatsiklopedia',
            'mk': u'Нециклопедий',
            'mo': u'Neciclopedia',
            'ms': u'Bodohpedia',
            'nl': u'Oncyclopedia',
            'nn': u'Ikkepedia',
            'no': u'Ikkepedia',
            'oc': u'Oisquipedia',
            'pl': u'Nonsensopedia',
            'pt': u'Desciclopédia',
            'ro': u'Neciclopedie',
            'ru': u'Абсурдопедия',
            'sk': u'Necyklopédia',
            'sl': u'Butalopedija',
            'sr': u'Нециклопедија',
            'su': u'Goblogpedia Wiki',
            'sv': u'Psyklopedin',
            'th': u'ไร้สาระนุกรม',
            'tl': u'Pekepedia',
            'tr': u'Yansiklopedi',
            'uk': u'Інциклопедія',
            'yi': u'קיינציקלאָפעדיע',
            'zh': u'伪基百科',
            'zh-hk': u'偽基百科',
            'zh-tw': u'偽基百科',
            'zombie': u'Zombiepedia',
        }

        self.namespaces[5] = {
            '_default': u'Uncyclopedia talk',
            'ar': u'نقاش بيضيپيديا',
            'ast': u'Nunyepedia alderique',
            'bg': u'Oxypedia беседа',
            'bn': u'আনসাইক্লোপিডিয়া আলোচনা',
            'bs': u'Razgovor s Neciklopedija',
            'ca': u'Valenciclopèdia Discussió',
            'common': u'UnCommons talk',
            'cs': u'Necyklopedie diskuse',
            'cy': u'Sgwrs Celwyddoniadur',
            'da': u'Spademanns Leksikon-diskussion',
            'de': u'Uncyclopedia Diskussion',
            'el': u'Φρικηπαίδεια συζήτηση',
            'eo': u'Neciklopedio diskuto',
            'es': u'Inciclopedia Discusión',
            'et': u'Ebatsüklopeedia arutelu',
            'fa': u'بحث نانشنامه',
            'fi': u'Keskustelu Hikipediasta',
            'fr': u'Discussion Désencyclopédie',
            'ga': u'Plé Frithchiclipéid',
            'got': u'Unsaiklopedia talk',
            'he': u'שיחת איןציקלופדיה',
            'hr': u'Razgovor Neciklopedija',
            'hu': u'Unciklopédia-vita',
            'id': u'Pembicaraan Tolololpedia',
            'info': u'Uncyclopaedia talk',
            'it': u'Discussioni Nonciclopedia',
            'ja': u'Uncyclopedia‐ノート',
            'jv': u'Dhiskusi Ndhablek',
            'ka': u'Anciklopedia განხილვა',
            'km': u'ការពិភាក្សាអំពីUncyclopedia',
            'ko': u'백괴사전토론',
            'la': u'Disputatio Uncapaediae',
            'lb': u'Kengencyclopedia Diskussioun',
            'li': u'Euverlèk Kwatsjpedia',
            'lo': u'ສົນທະນາກ່ຽວກັບUncyclopedia',
            'lt': u'Juokopediją aptarimas',
            'lv': u'Neciklopēdija diskusija',
            'meta': u'UnMeta talk',
            'mg': u'Dinika amin\'ny Hatsiklopedia',
            'mk': u'Разговор за Нециклопедий',
            'mo': u'Discuţie Neciclopedia',
            'ms': u'Perbincangan Bodohpedia',
            'nl': u'Overleg Oncyclopedia',
            'nn': u'Ikkepedia-diskusjon',
            'no': u'Ikkepedia-diskusjon',
            'oc': u'Discussion Oisquipedia',
            'pl': u'Dyskusja Nonsensopedia',
            'pt': u'Desciclopédia Discussão',
            'ro': u'Discuţie Neciclopedie',
            'ru': u'Обсуждение Абсурдопедии',
            'sk': u'Diskusia k Necyklopédia',
            'sl': u'Pogovor o Butalopedija',
            'sr': u'Разговор о Нециклопедија',
            'su': u'Obrolan Goblogpedia Wiki',
            'sv': u'Psyklopedindiskussion',
            'th': u'คุยเรื่องไร้สาระนุกรม',
            'tl': u'Usapang Pekepedia',
            'tr': u'Yansiklopedi tartışma',
            'uk': u'Обговорення Інциклопедії',
            'yi': u'קיינציקלאָפעדיע רעדן',
            'zh': u'伪基百科 talk',
            'zh-hk': u'偽基百科討論',
            'zh-tw': u'偽基百科討論',
            'zombie': u'Zombiepedia talk',
        }

        self.namespaces[6] = {
            '_default': u'File',
            'ar': u'ملف',
            'ast': u'Archivu',
            'bg': u'Файл',
            'bn': u'চিত্র',
            'bs': u'Datoteka',
            'ca': u'Fitxer',
            'common': u'Image',
            'cs': u'Soubor',
            'da': u'Fil',
            'de': u'Datei',
            'el': u'Αρχείο',
            'eo': u'Dosiero',
            'es': u'Archivo',
            'et': u'Pilt',
            'fa': u'پرونده',
            'fi': u'Tiedosto',
            'fr': u'Fichier',
            'ga': u'Íomhá',
            'he': u'קובץ',
            'hr': u'Datoteka',
            'hu': u'Fájl',
            'id': u'Berkas',
            'ja': u'ファイル',
            'jv': u'Gambar',
            'ka': u'ფაილი',
            'km': u'ឯកសារ',
            'ko': u'파일',
            'la': u'Fasciculus',
            'lb': u'Fichier',
            'li': u'Plaetje',
            'lo': u'ຮູບ',
            'lt': u'Vaizdas',
            'lv': u'Attēls',
            'mg': u'Sary',
            'mk': u'Податотека',
            'mo': u'Fişier',
            'ms': u'Fail',
            'nl': u'Bestand',
            'nn': u'Fil',
            'no': u'Fil',
            'oc': u'Fichièr',
            'pl': u'Plik',
            'pt': u'Imagem',
            'ro': u'Fişier',
            'ru': u'Файл',
            'sk': u'Súbor',
            'sl': u'Slika',
            'sr': u'Слика',
            'su': u'Gambar',
            'sv': u'Fil',
            'th': u'ไฟล์',
            'tl': u'Talaksan',
            'tr': u'Dosya',
            'uk': u'Файл',
            'yi': u'טעקע',
            'zh-hk': u'圖像',
            'zh-tw': u'圖像',
        }

        self.namespaces[7] = {
            '_default': u'File talk',
            'ar': u'نقاش الملف',
            'ast': u'Archivu alderique',
            'bg': u'Файл беседа',
            'bn': u'চিত্র আলোচনা',
            'bs': u'Razgovor o datoteci',
            'ca': u'Fitxer Discussió',
            'common': u'Image talk',
            'cs': u'Soubor diskuse',
            'da': u'Fildiskussion',
            'de': u'Datei Diskussion',
            'el': u'Συζήτηση αρχείου',
            'eo': u'Dosiera diskuto',
            'es': u'Archivo Discusión',
            'et': u'Pildi arutelu',
            'fa': u'بحث پرونده',
            'fi': u'Keskustelu tiedostosta',
            'fr': u'Discussion fichier',
            'ga': u'Plé íomhá',
            'he': u'שיחת קובץ',
            'hr': u'Razgovor o datoteci',
            'hu': u'Fájlvita',
            'id': u'Pembicaraan Berkas',
            'it': u'Discussioni file',
            'ja': u'ファイル‐ノート',
            'jv': u'Dhiskusi Gambar',
            'ka': u'ფაილის განხილვა',
            'km': u'ការពិភាក្សាអំពីឯកសារ',
            'ko': u'파일토론',
            'la': u'Disputatio Fasciculi',
            'lb': u'Fichier Diskussioun',
            'li': u'Euverlèk plaetje',
            'lo': u'ສົນທະນາກ່ຽວກັບຮູບ',
            'lt': u'Vaizdo aptarimas',
            'lv': u'Attēla diskusija',
            'mg': u'Dinika amin\'ny sary',
            'mk': u'Разговор за податотека',
            'mo': u'Discuţie Fişier',
            'ms': u'Perbincangan Fail',
            'nl': u'Overleg bestand',
            'nn': u'Fildiskusjon',
            'no': u'Fildiskusjon',
            'oc': u'Discussion Fichièr',
            'pl': u'Dyskusja pliku',
            'pt': u'Imagem Discussão',
            'ro': u'Discuţie Fişier',
            'ru': u'Обсуждение файла',
            'sk': u'Diskusia k súboru',
            'sl': u'Pogovor o sliki',
            'sr': u'Разговор о слици',
            'su': u'Obrolan gambar',
            'sv': u'Fildiskussion',
            'th': u'คุยเรื่องไฟล์',
            'tl': u'Usapang talaksan',
            'tr': u'Dosya tartışma',
            'uk': u'Обговорення файлу',
            'yi': u'טעקע רעדן',
            'zh-hk': u'圖像討論',
            'zh-tw': u'圖像討論',
        }

        self.namespaces[8] = {
            '_default': u'MediaWiki',
            'ar': u'ميدياويكي',
            'bg': u'МедияУики',
            'bn': u'মিডিয়াউইকি',
            'fa': u'مدیاویکی',
            'fi': u'Järjestelmäviesti',
            'he': u'מדיה ויקי',
            'ka': u'მედიავიკი',
            'km': u'មេឌាវិគី',
            'ko': u'미디어위키',
            'lo': u'ມີເດຍວິກິ',
            'mk': u'МедијаВики',
            'sr': u'МедијаВики',
            'su': u'MédiaWiki',
            'th': u'มีเดียวิกิ',
            'tr': u'MedyaViki',
            'yi': u'מעדיעװיקי',
            'zh-hk': u'媒體偽基',
            'zh-tw': u'媒體偽基',
        }

        self.namespaces[9] = {
            '_default': u'MediaWiki talk',
            'ar': u'نقاش ميدياويكي',
            'ast': u'MediaWiki alderique',
            'bg': u'МедияУики беседа',
            'bn': u'মিডিয়াউইকি আলোচনা',
            'bs': u'MediaWiki razgovor',
            'ca': u'MediaWiki Discussió',
            'cs': u'MediaWiki diskuse',
            'da': u'MediaWiki-diskussion',
            'de': u'MediaWiki Diskussion',
            'el': u'Συζήτηση MediaWiki',
            'eo': u'MediaWiki diskuto',
            'es': u'MediaWiki Discusión',
            'et': u'MediaWiki arutelu',
            'fa': u'بحث مدیاویکی',
            'fi': u'Keskustelu järjestelmäviestistä',
            'fr': u'Discussion MediaWiki',
            'ga': u'Plé MediaWiki',
            'he': u'שיחת מדיה ויקי',
            'hr': u'MediaWiki razgovor',
            'hu': u'MediaWiki-vita',
            'id': u'Pembicaraan MediaWiki',
            'it': u'Discussioni MediaWiki',
            'ja': u'MediaWiki‐ノート',
            'jv': u'Dhiskusi MediaWiki',
            'ka': u'მედიავიკის განხილვა',
            'km': u'ការពិភាក្សាអំពីមេឌាវិគី',
            'ko': u'미디어위키토론',
            'la': u'Disputatio MediaWiki',
            'lb': u'MediaWiki Diskussioun',
            'li': u'Euverlèk MediaWiki',
            'lo': u'ສົນທະນາກ່ຽວກັບມີເດຍວິກິ',
            'lt': u'MediaWiki aptarimas',
            'lv': u'MediaWiki diskusija',
            'mg': u'Dinika amin\'ny MediaWiki',
            'mk': u'Разговор за МедијаВики',
            'mo': u'Discuţie MediaWiki',
            'ms': u'Perbincangan MediaWiki',
            'nl': u'Overleg MediaWiki',
            'nn': u'MediaWiki-diskusjon',
            'no': u'MediaWiki-diskusjon',
            'oc': u'Discussion MediaWiki',
            'pl': u'Dyskusja MediaWiki',
            'pt': u'MediaWiki Discussão',
            'ro': u'Discuţie MediaWiki',
            'ru': u'Обсуждение MediaWiki',
            'sk': u'Diskusia k MediaWiki',
            'sl': u'Pogovor o MediaWiki',
            'sr': u'Разговор о МедијаВикију',
            'su': u'Obrolan MédiaWiki',
            'sv': u'MediaWiki-diskussion',
            'th': u'คุยเรื่องมีเดียวิกิ',
            'tl': u'Usapang MediaWiki',
            'tr': u'MedyaViki tartışma',
            'uk': u'Обговорення MediaWiki',
            'yi': u'מעדיעװיקי רעדן',
            'zh-hk': u'媒體偽基討論',
            'zh-tw': u'媒體偽基討論',
        }

        self.namespaces[10] = {
            '_default': u'Template',
            'ar': u'قالب',
            'ast': u'Plantía',
            'bg': u'Шаблон',
            'bn': u'টেমপ্লেট',
            'bs': u'Šablon',
            'ca': u'Plantilla',
            'cs': u'Šablona',
            'da': u'Skabelon',
            'de': u'Vorlage',
            'el': u'Πρότυπο',
            'eo': u'Ŝablono',
            'es': u'Plantilla',
            'et': u'Mall',
            'fa': u'الگو',
            'fi': u'Malline',
            'fr': u'Modèle',
            'ga': u'Teimpléad',
            'he': u'תבנית',
            'hr': u'Predložak',
            'hu': u'Sablon',
            'id': u'Templat',
            'jv': u'Cithakan',
            'ka': u'თარგი',
            'km': u'ទំព័រគំរូ',
            'ko': u'틀',
            'la': u'Formula',
            'lb': u'Schabloun',
            'li': u'Sjabloon',
            'lo': u'ແມ່ແບບ',
            'lt': u'Šablonas',
            'lv': u'Veidne',
            'mg': u'Endrika',
            'mk': u'Шаблон',
            'mo': u'Format',
            'ms': u'Templat',
            'nl': u'Sjabloon',
            'nn': u'Mal',
            'no': u'Mal',
            'oc': u'Modèl',
            'pl': u'Szablon',
            'pt': u'Predefinição',
            'ro': u'Format',
            'ru': u'Шаблон',
            'sk': u'Šablóna',
            'sl': u'Predloga',
            'sr': u'Шаблон',
            'su': u'Citakan',
            'sv': u'Mall',
            'th': u'แม่แบบ',
            'tl': u'Suleras',
            'tr': u'Şablon',
            'uk': u'Шаблон',
            'yi': u'מוסטער',
            'zh-hk': u'範本',
            'zh-tw': u'範本',
        }

        self.namespaces[11] = {
            '_default': u'Template talk',
            'ar': u'نقاش القالب',
            'ast': u'Plantía alderique',
            'bg': u'Шаблон беседа',
            'bn': u'টেমপ্লেট আলোচনা',
            'bs': u'Razgovor o šablonu',
            'ca': u'Plantilla Discussió',
            'cs': u'Šablona diskuse',
            'da': u'Skabelondiskussion',
            'de': u'Vorlage Diskussion',
            'el': u'Συζήτηση προτύπου',
            'eo': u'Ŝablona diskuto',
            'es': u'Plantilla Discusión',
            'et': u'Malli arutelu',
            'fa': u'بحث الگو',
            'fi': u'Keskustelu mallineesta',
            'fr': u'Discussion modèle',
            'ga': u'Plé teimpléid',
            'he': u'שיחת תבנית',
            'hr': u'Razgovor o predlošku',
            'hu': u'Sablonvita',
            'id': u'Pembicaraan Templat',
            'it': u'Discussioni template',
            'ja': u'Template‐ノート',
            'jv': u'Dhiskusi Cithakan',
            'ka': u'თარგის განხილვა',
            'km': u'ការពិភាក្សាអំពីទំព័រគំរូ',
            'ko': u'틀토론',
            'la': u'Disputatio Formulae',
            'lb': u'Schabloun Diskussioun',
            'li': u'Euverlèk sjabloon',
            'lo': u'ສົນທະນາກ່ຽວກັບແມ່ແບບ',
            'lt': u'Šablono aptarimas',
            'lv': u'Veidnes diskusija',
            'mg': u'Dinika amin\'ny endrika',
            'mk': u'Разговор за шаблон',
            'mo': u'Discuţie Format',
            'ms': u'Perbincangan Templat',
            'nl': u'Overleg sjabloon',
            'nn': u'Maldiskusjon',
            'no': u'Maldiskusjon',
            'oc': u'Discussion Modèl',
            'pl': u'Dyskusja szablonu',
            'pt': u'Predefinição Discussão',
            'ro': u'Discuţie Format',
            'ru': u'Обсуждение шаблона',
            'sk': u'Diskusia k šablóne',
            'sl': u'Pogovor o predlogi',
            'sr': u'Разговор о шаблону',
            'su': u'Obrolan citakan',
            'sv': u'Malldiskussion',
            'th': u'คุยเรื่องแม่แบบ',
            'tl': u'Usapang suleras',
            'tr': u'Şablon tartışma',
            'uk': u'Обговорення шаблону',
            'yi': u'מוסטער רעדן',
            'zh-hk': u'範本討論',
            'zh-tw': u'範本討論',
        }

        self.namespaces[12] = {
            '_default': u'Help',
            'ar': u'مساعدة',
            'ast': u'Aida',
            'bg': u'Помощ',
            'bn': u'সাহায্য',
            'bs': u'Pomoć',
            'ca': u'Ajuda',
            'cs': u'Nápověda',
            'da': u'Hjælp',
            'de': u'Hilfe',
            'el': u'Βοήθεια',
            'eo': u'Helpo',
            'es': u'Ayuda',
            'et': u'Juhend',
            'fa': u'راهنما',
            'fi': u'Ohje',
            'fr': u'Aide',
            'ga': u'Cabhair',
            'he': u'מדריך',
            'hr': u'Pomoć',
            'hu': u'Segítség',
            'id': u'Bantuan',
            'it': u'Aiuto',
            'jv': u'Pitulung',
            'ka': u'დახმარება',
            'km': u'ជំនួយ',
            'ko': u'도움말',
            'la': u'Auxilium',
            'lb': u'Hëllef',
            'lo': u'ຊ່ວຍເຫຼືອ',
            'lt': u'Pagalba',
            'lv': u'Palīdzība',
            'mg': u'Fanampiana',
            'mk': u'Помош',
            'mo': u'Ajutor',
            'ms': u'Bantuan',
            'nn': u'Hjelp',
            'no': u'Hjelp',
            'oc': u'Ajuda',
            'pl': u'Pomoc',
            'pt': u'Ajuda',
            'ro': u'Ajutor',
            'ru': u'Справка',
            'sk': u'Pomoc',
            'sl': u'Pomoč',
            'sr': u'Помоћ',
            'su': u'Pitulung',
            'sv': u'Hjälp',
            'th': u'วิธีใช้',
            'tl': u'Tulong',
            'tr': u'Yardım',
            'uk': u'Довідка',
            'yi': u'הילף',
            'zh-hk': u'協助',
            'zh-tw': u'協助',
        }

        self.namespaces[13] = {
            '_default': u'Help talk',
            'ar': u'نقاش المساعدة',
            'ast': u'Aida alderique',
            'bg': u'Помощ беседа',
            'bn': u'সাহায্য আলোচনা',
            'bs': u'Razgovor o pomoći',
            'ca': u'Ajuda Discussió',
            'cs': u'Nápověda diskuse',
            'da': u'Hjælp-diskussion',
            'de': u'Hilfe Diskussion',
            'el': u'Συζήτηση βοήθειας',
            'eo': u'Helpa diskuto',
            'es': u'Ayuda Discusión',
            'et': u'Juhendi arutelu',
            'fa': u'بحث راهنما',
            'fi': u'Keskustelu ohjeesta',
            'fr': u'Discussion aide',
            'ga': u'Plé cabhrach',
            'he': u'שיחת מדריך',
            'hr': u'Razgovor o pomoći',
            'hu': u'Segítségvita',
            'id': u'Pembicaraan Bantuan',
            'it': u'Discussioni aiuto',
            'ja': u'Help‐ノート',
            'jv': u'Dhiskusi Pitulung',
            'ka': u'დახმარების განხილვა',
            'km': u'ការពិភាក្សាអំពីជំនួយ',
            'ko': u'도움말토론',
            'la': u'Disputatio Auxilii',
            'lb': u'Hëllef Diskussioun',
            'li': u'Euverlèk help',
            'lo': u'ສົນທະນາກ່ຽວກັບຊ່ວຍເຫຼືອ',
            'lt': u'Pagalbos aptarimas',
            'lv': u'Palīdzības diskusija',
            'mg': u'Dinika amin\'ny fanampiana',
            'mk': u'Разговор за помош',
            'mo': u'Discuţie Ajutor',
            'ms': u'Perbincangan Bantuan',
            'nl': u'Overleg help',
            'nn': u'Hjelpdiskusjon',
            'no': u'Hjelpdiskusjon',
            'oc': u'Discussion Ajuda',
            'pl': u'Dyskusja pomocy',
            'pt': u'Ajuda Discussão',
            'ro': u'Discuţie Ajutor',
            'ru': u'Обсуждение справки',
            'sk': u'Diskusia k pomoci',
            'sl': u'Pogovor o pomoči',
            'sr': u'Разговор о помоћи',
            'su': u'Obrolan pitulung',
            'sv': u'Hjälpdiskussion',
            'th': u'คุยเรื่องวิธีใช้',
            'tl': u'Usapang tulong',
            'tr': u'Yardım tartışma',
            'uk': u'Обговорення довідки',
            'yi': u'הילף רעדן',
            'zh-hk': u'協助討論',
            'zh-tw': u'協助討論',
        }

        self.namespaces[14] = {
            '_default': u'Category',
            'ar': u'تصنيف',
            'ast': u'Categoría',
            'bg': u'Категория',
            'bn': u'বিষয়শ্রেণী',
            'bs': u'Kategorija',
            'ca': u'Categoria',
            'cs': u'Kategorie',
            'da': u'Kategori',
            'de': u'Kategorie',
            'el': u'Κατηγορία',
            'eo': u'Kategorio',
            'es': u'Categoría',
            'et': u'Kategooria',
            'fa': u'رده',
            'fi': u'Luokka',
            'fr': u'Catégorie',
            'ga': u'Catagóir',
            'he': u'קטגוריה',
            'hr': u'Kategorija',
            'hu': u'Kategória',
            'id': u'Kategori',
            'it': u'Categoria',
            'jv': u'Kategori',
            'ka': u'კატეგორია',
            'km': u'ចំនាត់ថ្នាក់ក្រុម',
            'ko': u'분류',
            'la': u'Categoria',
            'lb': u'Kategorie',
            'li': u'Categorie',
            'lo': u'ໝວດ',
            'lt': u'Kategorija',
            'lv': u'Kategorija',
            'mg': u'Sokajy',
            'mk': u'Категорија',
            'mo': u'Categorie',
            'ms': u'Kategori',
            'nl': u'Categorie',
            'nn': u'Kategori',
            'no': u'Kategori',
            'oc': u'Categoria',
            'pl': u'Kategoria',
            'pt': u'Categoria',
            'ro': u'Categorie',
            'ru': u'Категория',
            'sk': u'Kategória',
            'sl': u'Kategorija',
            'sr': u'Категорија',
            'su': u'Kategori',
            'sv': u'Kategori',
            'th': u'หมวดหมู่',
            'tl': u'Kaurian',
            'tr': u'Kategori',
            'uk': u'Категорія',
            'yi': u'קאַטעגאָריע',
            'zh-hk': u'分類',
            'zh-tw': u'分類',
        }

        self.namespaces[15] = {
            '_default': u'Category talk',
            'ar': u'نقاش التصنيف',
            'ast': u'Categoría alderique',
            'bg': u'Категория беседа',
            'bn': u'বিষয়শ্রেণী আলোচনা',
            'bs': u'Razgovor o kategoriji',
            'ca': u'Categoria Discussió',
            'cs': u'Kategorie diskuse',
            'da': u'Kategoridiskussion',
            'de': u'Kategorie Diskussion',
            'el': u'Συζήτηση κατηγορίας',
            'eo': u'Kategoria diskuto',
            'es': u'Categoría Discusión',
            'et': u'Kategooria arutelu',
            'fa': u'بحث رده',
            'fi': u'Keskustelu luokasta',
            'fr': u'Discussion catégorie',
            'ga': u'Plé catagóire',
            'he': u'שיחת קטגוריה',
            'hr': u'Razgovor o kategoriji',
            'hu': u'Kategóriavita',
            'id': u'Pembicaraan Kategori',
            'it': u'Discussioni categoria',
            'ja': u'Category‐ノート',
            'jv': u'Dhiskusi Kategori',
            'ka': u'კატეგორიის განხილვა',
            'km': u'ការពិភាក្សាអំពីចំនាត់ថ្នាក់ក្រុម',
            'ko': u'분류토론',
            'la': u'Disputatio Categoriae',
            'lb': u'Kategorie Diskussioun',
            'li': u'Euverlèk categorie',
            'lo': u'ສົນທະນາກ່ຽວກັບໝວດ',
            'lt': u'Kategorijos aptarimas',
            'lv': u'Kategorijas diskusija',
            'mg': u'Dinika amin\'ny sokajy',
            'mk': u'Разговор за категорија',
            'mo': u'Discuţie Categorie',
            'ms': u'Perbincangan Kategori',
            'nl': u'Overleg categorie',
            'nn': u'Kategoridiskusjon',
            'no': u'Kategoridiskusjon',
            'oc': u'Discussion Categoria',
            'pl': u'Dyskusja kategorii',
            'pt': u'Categoria Discussão',
            'ro': u'Discuţie Categorie',
            'ru': u'Обсуждение категории',
            'sk': u'Diskusia ku kategórii',
            'sl': u'Pogovor o kategoriji',
            'sr': u'Разговор о категорији',
            'su': u'Obrolan kategori',
            'sv': u'Kategoridiskussion',
            'th': u'คุยเรื่องหมวดหมู่',
            'tl': u'Usapang kaurian',
            'tr': u'Kategori tartışma',
            'uk': u'Обговорення категорії',
            'yi': u'קאַטעגאָריע רעדן',
            'zh-hk': u'分類討論',
            'zh-tw': u'分類討論',
        }

        self.namespaces[16] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[17] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[18] = {
            '_default': '',
            'fi': u'Hikinews',
            'got': u'𐌰𐍂𐌼𐌰𐌹𐍉',
            'meta': u'UnSpecies',
            'nl': u'OnNieuws',
            'pt': u'Fatos',
            'th': u'ไร้ข่าว',
            'zh-hk': u'偽基辭典',
            'zh-tw': u'偽基辭典',
        }

        self.namespaces[19] = {
            '_default': '',
            'fi': u'Hikinews',
            'got': u'𐌰𐍂𐌼𐌰𐌹𐍉',
            'meta': u'UnSpecies',
            'nl': u'OnNieuws',
            'pt': u'Fatos',
            'th': u'ไร้ข่าว',
            'zh-hk': u'偽基辭典',
            'zh-tw': u'偽基辭典',
        }

        self.namespaces[20] = {
            '_default': '',
            'fi': u'Hikinews',
            'got': u'𐌰𐍂𐌼𐌰𐌹𐍉',
            'meta': u'UnSpecies',
            'nl': u'OnNieuws',
            'pt': u'Fatos',
            'th': u'ไร้ข่าว',
            'zh-hk': u'偽基辭典',
            'zh-tw': u'偽基辭典',
        }

        self.namespaces[21] = {
            '_default': '',
            'fi': u'Keskustelu Hiktionarysta',
            'got': u'𐍆𐌰𐌹𐌰𐌽𐍅𐌰𐌿𐍂𐌳𐌰𐌱𐍉𐌺𐌰 𐌲𐌰𐍅𐌰𐌿𐍂𐌳𐌾𐌰',
            'nl': u'Overleg Onwoordenboek',
            'pt': u'Forum Discussão',
            'th': u'คุยเรื่องไร้วิทยาลัย',
            'zh-hk': u'動漫遊戲討論',
            'zh-tw': u'動漫遊戲討論',
        }

        self.namespaces[22] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[23] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[24] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[25] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[26] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[27] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[28] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[29] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[30] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[31] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[32] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[33] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[34] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[35] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[36] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[37] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[100] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[101] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[102] = {
            '_default': u'UnNews',
            'de': u'Undictionary',
            'ko': u'포럼',
            'nn': u'Ikktionary',
            'no': u'Ikktionary',
            'pl': u'NonNews',
            'sv': u'Forum',
            'tr': u'YanHaber',
        }

        self.namespaces[103] = {
            '_default': u'UnNews talk',
            'de': u'Undictionary Diskussion',
            'ko': u'포럼토론',
            'nn': u'Ikktionary-diskusjon',
            'no': u'Ikktionary-diskusjon',
            'pl': u'Dyskusja NonNews',
            'sv': u'Forumdiskussion',
            'tr': u'YanHaber tartışma',
        }

        self.namespaces[104] = {
            '_default': u'Undictionary',
            'de': u'UnBooks',
            'ko': u'백괴뉴스',
            'pl': u'Nonźródła',
            'sv': u'Psyktionary',
        }

        self.namespaces[105] = {
            '_default': u'Undictionary talk',
            'de': u'UnBooks Diskussion',
            'ko': u'백괴뉴스토론',
            'pl': u'Dyskusja nonźródeł',
            'sv': u'Psyktionary diskussion',
        }

        self.namespaces[106] = {
            '_default': 'Game',
            'ko': u'백괴낱말사전',
            'pl': u'Słownik',
            'pt': u'Desnotícias',
            'sv': u'PsykCitat',
        }

        self.namespaces[107] = {
            '_default': u'Game talk',
            'ko': u'백괴낱말사전토론',
            'pl': u'Dyskusja słownika',
            'pt': u'Desnotícias Discussão',
            'sv': u'PsykCitat diskussion',
        }

        self.namespaces[108] = {
            '_default': u'Babel',
            'ko': u'해설',
            'pl': u'Gra',
            'pt': u'Jogo',
            'sv': u'Spel',
        }

        self.namespaces[109] = {
            '_default': u'Babel talk',
            'ko': u'해설토론',
            'pl': u'Dyskusja gry',
            'pt': u'Jogo Discussão',
            'sv': u'Speldiskussion',
        }

        self.namespaces[110] = {
            '_default': u'Forum',
            'he': u'בית קפה',
            'ko': u'백괴식당',
            'pt': u'Descionário',
            'ru': u'Форум',
            'sv': u'PsykBöcker',
            'tr': u'Astroloji',
        }

        self.namespaces[111] = {
            '_default': u'Forum talk',
            'da': u'Forumdiskussion',
            'fr': u'Discussion Forum',
            'he': u'שיחת בית קפה',
            'ko': u'백괴식당토론',
            'pl': u'Dyskusja forum',
            'pt': u'Descionário Discussão',
            'ru': u'Обсуждение форума',
            'sv': u'PsykBöckerdiskussion',
            'tr': u'Astroloji tartışma',
        }

        self.namespaces[112] = {
            '_default': u'UnTunes',
            'cs': u'Regál',
            'es': u'Incinoticias',
            'fr': u'Désinformation',
            'he': u'איןספר',
            'it': u'NonNotizie',
            'ko': u'백괴우주',
            'nn': u'Hvordan',
            'no': u'Hvordan',
            'pl': u'Portal',
            'tr': u'Forum',
            'zh': u'伪基新闻',
        }

        self.namespaces[113] = {
            '_default': u'UnTunes talk',
            'cs': u'Regál diskuse',
            'es': u'Incinoticias Discusión',
            'fr': u'Discussion Désinformation',
            'he': u'שיחת איןספר',
            'it': u'Discussioni NonNotizie',
            'ko': u'백괴우주토론',
            'nn': u'Hvordan-diskusjon',
            'no': u'Hvordan-diskusjon',
            'pl': u'Dyskusja portalu',
            'tr': u'Forum tartışma',
            'zh': u'伪基新闻 talk',
        }

        self.namespaces[114] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[115] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[116] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[117] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[118] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[119] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[120] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[121] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[122] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[123] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[124] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[125] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[400] = {
            '_default': u'Video',
            'ru': u'Видео',
        }

        self.namespaces[401] = {
            '_default': u'Video talk',
            'ru': u'Обсуждение видео',
        }

        self.namespaces[402] = {
            '_default': u'',
            'cs': u'Necykloverzita',
            'de': u'UnNews Diskussion',
            'es': u'Incijuegos',
            'et': u'Foorum',
            'fi': u'Keskustelu hikiaineistosta',
            'fr': u'Portail',
            'got': u'Forum',
            'he': u'שיחת איןציטוט',
            'info': u'Game',
            'it': u'Discussioni NonDizionario',
            'ja': u'Portal',
            'ko': u'백괴게임토론',
            'meta': u'UnSource',
            'nl': u'Oncycloversiteit',
            'nn': u'Ikkenytt-diskusjon',
            'no': u'Ikkenytt-diskusjon',
            'pl': u'Dyskusja cytatów',
            'pt': u'Regra Discussão',
            'sv': u'PsykNyheter diskussion',
            'th': u'คุยเรื่องไร้คำคม',
            'tr': u'YanSözlük tartışma',
            'zh': u'伪基词典',
            'zh-hk': u'香港語討論',
            'zh-tw': u'香港語討論',
        }

        self.namespaces[500] = {
            '_default': u'User blog',
            'de': u'Benutzer Blog',
            'ru': u'Блог участника',
        }

        self.namespaces[501] = {
            '_default': u'User blog comment',
            'de': u'Benutzer Blog Kommentare',
            'ru': u'Комментарий блога участника',
        }

        self.namespaces[502] = {
            '_default': u'Blog',
            'ru': u'Блог',
        }

        self.namespaces[503] = {
            '_default': u'Blog talk',
            'de': u'Blog Diskussion',
            'ru': u'Обсуждение блога',
        }


        # A few selected big languages for things that we do not want to loop over
        # all languages. This is only needed by the titletranslate.py module, so
        # if you carefully avoid the options, you could get away without these
        # for another wiki family.
        self.languages_by_size  = [
            'en','pt','ja','pl','it','fr','es','fi','zh-tw','zh-hk','de','da','no',
            'ko','ru','th','el','cs','he','zh','sv','hu','nl','id','ar','sk','uk',
            'eo','tr','ca','fa','hr','sr','lt','tl','lv','bg','la','ro','ms','ast',
            'mk','cy','et','sl','mo','bs','mg','yi','ka','got','zombie','bn','li',
            'km','lb','lo','su','jv','ga','oc'
        ]

        self.alphabetic_revised = [
            'ar','ast','bg','bn','bs','ca','common','cs','cy','da','de','el','en',
            'eo','es','et','fa','fi','fr','ga','got','he','hr','hu','id','info','it',
            'ja','jv','ka','km','ko','la','lb','li','lo','lt','lv','meta','mg','mk',
            'mo','ms','nl','nn','no','oc','pl','pt','ro','ru','sk','sl','sr','su',
            'sv','th','tl','tr','uk','yi','zh-hk','zh-tw','zh','zombie',
        ]


    def scriptpath(self, code):
        if code == 'ko':
            return '/w'
        return ''

    def version(self, code):
        return '1.12'

    def code2encoding(self,code):
        return 'utf-8'

    def shared_image_repository(self, code):
        return ('common', 'common')
